apiVersion: v1
kind: Service
metadata:
  name: {{ include "sba.name" . }}
  labels:
    {{- include "sba.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "sba.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
