replicaCount: 1

image:
  repository: ghcr.io/german4341374/support-bundle-analyzer
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  port: 8080

auth:
  existingSecret: support-bundle-analyzer-auth
  tokenKey: access-token

analysisTimeoutSeconds: 900

persistence:
  enabled: true
  size: 2Gi
  storageClass: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 1Gi

ingress:
  enabled: false
  className: nginx
  host: analyzer.local

networkPolicy:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1
